QT.avwidgets_private.VERSION = 5.3.0
QT.avwidgets_private.MAJOR_VERSION = 5
QT.avwidgets_private.MINOR_VERSION = 3
QT.avwidgets_private.PATCH_VERSION = 0
QT.avwidgets_private.name = QtAVWidgets
QT.avwidgets_private.libs = $$QT_MODULE_LIB_BASE
QT.avwidgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtAVWidgets/5.3.0 $$QT_MODULE_INCLUDE_BASE/QtAVWidgets/5.3.0/QtAVWidgets
QT.avwidgets_private.depends = avwidgets
QT.avwidgets_private.module_config = internal_module no_link
